# Generated by Django 6.0.2 on 2026-04-04 19:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'hôtel")),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('country', models.CharField(default='Tunisie', max_length=100, verbose_name='Pays')),
                ('address', models.TextField(verbose_name='Adresse exacte')),
                ('price_per_night', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Prix par nuit (TND)')),
                ('description', models.TextField(blank=True, verbose_name='Description détaillée')),
                ('stars', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name="Nombre d'étoiles")),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotels/', verbose_name='Image de couverture')),
                ('has_wifi', models.BooleanField(default=True, verbose_name='Accès WiFi')),
                ('has_pool', models.BooleanField(default=True, verbose_name='Piscine')),
                ('has_parking', models.BooleanField(default=True, verbose_name='Parking gratuit')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
            ],
            options={
                'verbose_name': 'Hôtel',
                'verbose_name_plural': 'Hôtels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('SINGLE', 'Single Room'), ('DOUBLE', 'Double Room'), ('SUITE', 'Suite'), ('COUPLE', 'Couple Room')], default='DOUBLE', max_length=20)),
                ('max_adults', models.IntegerField(default=2)),
                ('max_children', models.IntegerField(default=1)),
                ('max_babies', models.IntegerField(default=1)),
                ('price_per_night', models.DecimalField(decimal_places=3, max_digits=10)),
                ('price_per_child', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rooms/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='hotels.room')),
            ],
            options={
                'verbose_name': 'Image de Chambre',
                'verbose_name_plural': 'Images de Chambres',
            },
        ),
        migrations.CreateModel(
            name='SeasonalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la saison')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price_per_night', models.DecimalField(decimal_places=3, max_digits=10)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasonal_prices', to='hotels.room')),
            ],
            options={
                'verbose_name': 'Prix Saisonnier',
                'verbose_name_plural': 'Prix Saisonniers',
            },
        ),
    ]
