# Generated by Django 6.0.2 on 2026-04-13 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=200, verbose_name='Nom du client')),
                ('guest_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('guest_phone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('check_in_date', models.DateField(verbose_name="Date d'arrivée")),
                ('check_out_date', models.DateField(verbose_name='Date de départ')),
                ('number_of_adults', models.IntegerField(default=1, verbose_name="Nombre d'adultes")),
                ('number_of_children', models.IntegerField(default=0, verbose_name="Nombre d'enfants")),
                ('number_of_babies', models.IntegerField(default=0, verbose_name='Nombre de bébés')),
                ('total_price', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Prix total (TND)')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de réservation')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hotels.room')),
            ],
            options={
                'verbose_name': 'Réservation Hôtel',
                'verbose_name_plural': 'Réservations Hôtel',
                'ordering': ['-created_at'],
            },
        ),
    ]
