# Generated by Django 6.0.2 on 2026-04-04 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du voyage')),
                ('description', models.TextField(verbose_name='Description générale')),
                ('base_price', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Prix à partir de (TND)')),
                ('duration_nights', models.IntegerField(default=7, verbose_name='Nombre de nuits')),
                ('inclusions', models.TextField(verbose_name='Ce prix comprend')),
                ('exclusions', models.TextField(verbose_name='Ce prix ne comprend pas')),
                ('image', models.ImageField(upload_to='tours/', verbose_name='Image principale')),
            ],
            options={
                'verbose_name': 'Voyage Organisé',
                'verbose_name_plural': 'Voyages Organisés',
            },
        ),
        migrations.CreateModel(
            name='TourInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('HOTEL', 'Hôtel'), ('FLIGHT', 'Vol'), ('VISIT', 'Visite')], max_length=50)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='tours.tour')),
            ],
        ),
        migrations.CreateModel(
            name='ItineraryDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(verbose_name='Jour n°')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la journée')),
                ('content', models.TextField(verbose_name='Détails du programme')),
                ('accommodation', models.CharField(blank=True, max_length=255, verbose_name='Hébergement prévu')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='tours.tour')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('tour', 'day_number')},
            },
        ),
    ]
