# Generated by Django 6.0.2 on 2026-04-04 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'aéroport")),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code IATA')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(max_length=100, verbose_name='Compagnie aérienne')),
                ('flight_number', models.CharField(max_length=20, verbose_name='Numéro de vol')),
                ('departure_time', models.DateTimeField(verbose_name='Heure de départ')),
                ('arrival_time', models.DateTimeField(verbose_name="Heure d'arrivée")),
                ('is_direct', models.BooleanField(default=True, verbose_name='Vol Direct')),
                ('stops_count', models.IntegerField(default=0, verbose_name="Nombre d'escales")),
                ('price', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Prix (TND)')),
                ('seats_remaining', models.IntegerField(default=0, verbose_name='Sièges restants')),
                ('is_refundable', models.BooleanField(default=False, verbose_name='Remboursable')),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='flights.airport')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='flights.airport')),
            ],
            options={
                'verbose_name': 'Vol',
                'ordering': ['price'],
            },
        ),
    ]
