# Generated by Django 6.0.2 on 2026-03-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('transmission', models.CharField(choices=[('MANUAL', 'Manuelle'), ('AUTOMATIC', 'Automatique')], default='MANUAL', max_length=20)),
                ('fuel_type', models.CharField(choices=[('GASOLINE', 'Essence'), ('DIESEL', 'Diesel'), ('HYBRID', 'Hybride'), ('ELECTRIC', 'Électrique')], default='GASOLINE', max_length=20)),
                ('seats', models.PositiveIntegerField(default=5)),
                ('price_per_day', models.DecimalField(decimal_places=3, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/')),
            ],
        ),
    ]
