# Generated by Django 6.0.2 on 2026-04-05 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='license_plate',
        ),
    ]
