# Generated by Django 6.0.2 on 2026-04-04 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0002_booking'),
        ('flights', '0001_initial'),
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('start_date', models.DateField(verbose_name='Date de début / Check-in')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin / Check-out')),
                ('total_price', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Prix Total (TND)')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmée'), ('CANCELLED', 'Annulée')], default='PENDING', max_length=20, verbose_name='Statut du dossier')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.car', verbose_name='Voiture de location')),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.flight', verbose_name='Vol')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotels.room', verbose_name="Chambre d'hôtel")),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-booking_date'],
            },
        ),
    ]
